name: Swift Lint

on:
  pull_request:
    paths:
      - ".github/workflows/swiftlint.yml"
      - ".swiftlint.yml"
      - "RxReachability-Example/**/*.swift"
      - "Sources/**/*.swift"
      - "Tests/**/*.swift"

jobs:
  swift-lint:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1

      # - name: Danger
      #   uses: danger/swift@2.0.3
      #   env:
      #     GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: GitHub Action for SwiftLint
        uses: norio-nomura/action-swiftlint@3.1.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
